root = "." # The root directory of the project
tmp_dir = "tmp" # The temporary directory where air will store its temporary files

[build] # The build configuration
  bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ."
  exclude = ["tmp/*", "client/*"]  # Specifies the directories to be excluded from monitoring for changes
  include = ["**/*.go"] # Specifies the file patterns to be included for monitoring.
  ignore = ["tmp/*"] # Specifies the files or directories to be ignored when triggering a build.